repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.6
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args: ['--args=--sort-by required']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: mixed-line-ending
      args: ['--fix=lf']
